---
title: "Class Project"
author: "Sorie Yillah"
date: "4/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Imports go here
library(tidyverse)
library(Lahman)
library(lubridate)
library(baseballr)
library(mgcv)
library(lme4)
library(broom)
library(modelr)
library(glue)
library(plotly)
library(ggrepel)
```

```{r}
#pulls 2016 data from Statcast. One row per pitch hit into play
start_dates <- seq(ymd("2016-04-03"), ymd("2016-09-30"), by = "10 days")
end_dates <- start_dates + 9

hit_into_play2016 <- map2_dfr(start_dates, end_dates, scrape_statcast_savant) %>% 
  filter(description == "hit_into_play") %>% 
  filter(launch_speed < 150,
         launch_speed > 0,
         launch_angle < 360)


```

```{r}
#hit_into_play2016 %>%
#  write.csv(.,"C:\\Users\\garrett.whitener\\OneDrive - West Point\\2. Cow\\MA388\\Sabermetrics\\class project\\MA388_Project\\projectdata.csv", row.names = FALSE)


#creates HR probability model based on batting launch angle and speed
model.location = gam(events == "home_run" ~ s(launch_speed, launch_angle),
                     family = "binomial",
                     data = hit_into_play2016)

summary(model.location)


vars <- c("G", "AB","R", "H", "X2B","X3B","HR", "RBI", "BB", "SO", "SB",
          "SH", "HBP", "SF")

#gets player stats and joins with the naming convention of the batters
name_stats <- Batting %>%
  group_by(playerID) %>%
  summarize_at(vars,sum,na.rm = TRUE) %>%
  mutate(AVG = round(H/AB,3),
         HR.rate = HR/AB,
         PA = AB + BB + SH + HBP + SF) %>%
  left_join(People, by = "playerID")

#joins the player stats with the statcast data
#one row per pitch, adding the batter's seasonal batting stats each row
hit_into_play2016_stats = name_stats %>%
  mutate(player_name = paste(nameLast,nameFirst, sep = ", "))%>%
  left_join(hit_into_play2016, by = "player_name")
  
#fit random effects model adjusting for pitch location
hit_into_play2016_stats_model = model.location %>%
  augment(type.predict = "response",
          newdata = hit_into_play2016_stats) %>%
  rename(HR_prob = .fitted)

#create a random effects model with fixed effect fro batter and teh batter's BA
model_random_effects = glmer(events == "home_run" ~ HR_prob + (1|player_name) + AVG,
                             family = "binomial",
                             data = hit_into_play2016_stats)   #one with vertical line indicated random effect
summary(model_random_effects)

```

